"use client";

import JSZip from "jszip";
import type { Project } from "./schema";
import { generateBundle } from "./generators";
import { markdownToDocxBlob } from "./docx";
import { generateScaffold } from "./scaffold";

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "untitled"
  );
}

export function downloadFile(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: mime });
  triggerBlobDownload(blob, filename);
}

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function downloadProjectBundle(project: Project) {
  const zip = new JSZip();
  const root = zip.folder(`${slug(project.name)}-bundle`)!;
  const md = root.folder("markdown")!;
  const docx = root.folder("docx")!;
  const artifacts = generateBundle(project);

  for (const a of artifacts) {
    md.file(a.filename, a.body);
    const blob = await markdownToDocxBlob(a.title, a.body);
    docx.file(a.filename.replace(/\.md$/, ".docx"), blob);
  }

  const scaffoldFolder = root.folder("scaffold")!;
  for (const file of generateScaffold(project)) {
    scaffoldFolder.file(file.path, file.content);
  }

  root.file("project.json", JSON.stringify(project, null, 2));
  root.file(
    "README.md",
    [
      `# ${project.name || "Untitled project"} — bundle`,
      ``,
      project.oneLiner ? `> ${project.oneLiner}` : "",
      ``,
      `Generated by Product Dev Blueprint. All artifacts derive from \`project.json\` — change the schema and regenerate to keep them consistent.`,
      ``,
      `## What's inside`,
      ``,
      `- \`markdown/\` — version-control friendly source for every artifact`,
      `- \`docx/\` — Word-compatible deliverables for every artifact`,
      `- \`scaffold/\` — boilerplate folder structure, README, .env.example, docker-compose, and CI stub matching your platform choices`,
      `- \`project.json\` — raw canonical schema (regenerate the bundle from this)`,
      ``,
      `## Artifacts`,
      ``,
      ...artifacts.map((a) => `- \`${a.filename}\` — ${a.title}: ${a.description}`),
      ``,
      `Drafts only — human review required before publication.`,
    ].join("\n"),
  );
  const blob = await zip.generateAsync({ type: "blob" });
  triggerBlobDownload(blob, `${slug(project.name)}-bundle.zip`);
}

export function downloadProjectJSON(project: Project) {
  downloadFile(
    `${slug(project.name)}.json`,
    JSON.stringify(project, null, 2),
    "application/json",
  );
}
