"use client";

import JSZip from "jszip";
import type { Project } from "./schema";
import { generateBundle } from "./generators";

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "untitled"
  );
}

export function downloadFile(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function downloadProjectBundle(project: Project) {
  const zip = new JSZip();
  const root = zip.folder(`${slug(project.name)}-bundle`)!;
  const artifacts = generateBundle(project);
  artifacts.forEach((a) => root.file(a.filename, a.body));
  root.file("project.json", JSON.stringify(project, null, 2));
  root.file(
    "README.md",
    [
      `# ${project.name || "Untitled project"} — bundle`,
      ``,
      project.oneLiner ? `> ${project.oneLiner}` : "",
      ``,
      `Generated by Product Dev Blueprint. All artifacts derive from \`project.json\` — change the schema and regenerate to keep them consistent.`,
      ``,
      `## Files`,
      ``,
      ...artifacts.map((a) => `- \`${a.filename}\` — ${a.title}: ${a.description}`),
      ``,
      `Drafts only — human review required before publication.`,
    ].join("\n"),
  );
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slug(project.name)}-bundle.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
