import { Project } from "../schema";
import { header } from "./util";

export function generateCodingAgentPrompts(p: Project): string {
  const features = p.functional.features;
  const stack = stackSummary(p);

  const out: string[] = [
    header(p, `Coding-agent prompt pack — ${p.name || "Untitled"}`, "Prompt pack"),
    `These prompts are designed to be pasted directly into Cursor, Lovable, Replit Agent, Claude Code, or similar coding agents.`,
    ``,
    `Each prompt is self-contained and references only this bundle's documents — paste the bundle into the agent's context, then run the prompts in order.`,
    ``,
    `## 0. Project context (paste first)`,
    ``,
    `\`\`\`text`,
    `You are an experienced full-stack engineer. We are building "${p.name || "Untitled project"}".`,
    ``,
    `One-liner: ${p.oneLiner || "(none)"}.`,
    ``,
    `Idea: ${p.ideaDescription || "(see PRD)"}`,
    ``,
    `Stack:`,
    stack,
    ``,
    `Reference documents in the bundle (read these before responding):`,
    `- 02-prd.md`,
    `- 03-sow.md`,
    `- 04-tech-spec.md`,
    `- 05-adr-pack.md`,
    `- 06-data-interface-spec.md`,
    `- 07-rtm.md`,
    `- 08-test-strategy.md`,
    `- 09-launch-ops.md`,
    `- 11-risk-register.md`,
    `- 15-feature-spec.md`,
    `- 16-implementation-roadmap.md`,
    ...(p.ai.needsAI ? [`- 13-ai-architecture.md`] : []),
    ``,
    `Constraints:`,
    `- Match the technical spec and ADRs. If you must deviate, surface a new ADR proposal in your response and stop.`,
    `- Do not introduce new dependencies without listing them and the reason.`,
    `- Every requirement is anchored by an ID (FR-/NFR-/FEAT-). Reference the IDs you implement.`,
    `\`\`\``,
    ``,
    `## 1. Repository scaffolding`,
    ``,
    `\`\`\`text`,
    `Create the initial repository for the project above. Use the stack already chosen.`,
    ``,
    `Output, in this order:`,
    `1. The full file tree.`,
    `2. package.json / pyproject.toml / build files with pinned versions.`,
    `3. .env.example with every variable required, grouped by service.`,
    `4. README with setup, run, test, and deploy commands.`,
    `5. CI workflow (lint, type-check, test, build, container build).`,
    `6. Dockerfile(s) and docker-compose for local dev with the database and cache.`,
    `7. A "FIRST RUN" checklist a new contributor follows in <15 minutes.`,
    ``,
    `Do NOT generate feature code yet — just scaffolding.`,
    `\`\`\``,
    ``,
    `## 2. Data model & migrations`,
    ``,
    `\`\`\`text`,
    `Implement the canonical data model from 06-data-interface-spec.md.`,
    ``,
    `For each entity (ENT-NNN):`,
    `- Define the table / collection with explicit types and constraints.`,
    `- Mark sensitive columns and add encryption-at-rest where applicable.`,
    `- Add retention policies as scheduled jobs / TTL where the spec requires it.`,
    ``,
    `Generate:`,
    `1. Migration files (versioned, reversible).`,
    `2. ORM models / typed clients.`,
    `3. Seed data for local dev (no production data).`,
    `4. A diagram (Mermaid) of relationships.`,
    `5. Tests verifying constraints and migrations.`,
    `\`\`\``,
    ``,
    `## 3. Authentication & RBAC`,
    ``,
    `\`\`\`text`,
    `Implement authentication using ${p.platform.authMethod} and RBAC per the technical spec.`,
    ``,
    `Deliverables:`,
    `1. Sign-up, sign-in, password reset (or magic link), session lifecycle.`,
    `2. Middleware enforcing role on every protected route.`,
    `3. Role definitions and a seed role-mapping fixture.`,
    `4. Audit-log entries for auth events.`,
    `5. Integration tests for happy and unauthorized paths per role.`,
    ``,
    `Do not roll your own crypto. Use the framework's recommended primitives.`,
    `\`\`\``,
    ``,
    `## 4. Feature implementation prompts`,
    ``,
  ];

  if (features.length === 0) {
    out.push("_No features captured yet — populate the Feature Builder step to generate per-feature prompts._", "");
  } else {
    features.forEach((f) => {
      out.push(
        `### ${f.id} — ${f.name || "Untitled feature"}`,
        ``,
        "```text",
        `Implement ${f.id} (${f.name || "untitled feature"}).`,
        ``,
        `User story: ${f.userStory || "(see feature spec)"}`,
        ``,
        `Acceptance criteria: ${f.acceptance || "(see feature spec — capture before implementing)"}`,
        ``,
        `Constraints:`,
        `- Priority: ${f.priority}; complexity: ${f.complexity}; release: ${f.release}.`,
        `- Dependencies: ${f.dependencies || "(none stated)"}`,
        `- APIs needed: ${f.apisNeeded || "(decide and document)"}`,
        `- Data needed: ${f.dataNeeded || "(decide and document)"}`,
        `- Edge cases to handle: ${f.edgeCases || "(consult feature spec + general edge case list)"}`,
        `- Error states: ${f.errorStates || "(define and surface to UI)"}`,
        `- Admin controls: ${f.adminControls || "(none stated)"}`,
        `- Audit / logging: ${f.audit || "(log per project audit policy)"}`,
        `- Security: ${f.security || "(apply default RBAC + input validation)"}`,
        ``,
        `Deliverables:`,
        `1. Backend endpoints and services.`,
        `2. Frontend UI matching the experience surface.`,
        `3. Unit tests for logic, integration tests for the endpoint, end-to-end test for the user journey.`,
        `4. Update the API spec and traceability matrix to reference this feature ID.`,
        `5. Document any new ADR for non-trivial decisions.`,
        "```",
        ``,
      );
    });
  }

  out.push(
    `## 5. SLO instrumentation`,
    ``,
    "```text",
    `Wire SLO instrumentation for the surfaces below. For each, expose:`,
    `- Latency histogram (p50/p95/p99).`,
    `- Error rate (4xx vs 5xx separated).`,
    `- Throughput.`,
    ``,
    `Surfaces & targets:`,
    p.nonfunctional.slos.length === 0
      ? `- (No SLOs captured — define before launch.)`
      : p.nonfunctional.slos.map((s) => `- ${s.id}: ${s.surface} — ${s.metric} ${s.target}`).join("\n"),
    ``,
    `Hook these into the observability stack (${p.platform.observability || "OpenTelemetry"}). Add an alert when error budget burns above 2× normal.`,
    "```",
    ``,
    `## 6. Test strategy execution`,
    ``,
    "```text",
    `Implement the test strategy in 08-test-strategy.md.`,
    ``,
    `For every requirement (FR-/NFR-/FEAT-NNN), generate:`,
    `1. At least one acceptance scenario with arrange/act/assert.`,
    `2. At least one negative-path scenario.`,
    `3. Accessibility checks for any user-facing surface (keyboard, contrast, labels).`,
    ``,
    `Output a test matrix mapping requirement IDs → test names → file path.`,
    "```",
    ``,
    `## 7. Launch readiness`,
    ``,
    "```text",
    `Use 09-launch-ops.md to drive launch readiness.`,
    ``,
    `Deliverables:`,
    `1. Runbook covering common incidents (DB primary loss, region outage, third-party outage, cache cluster loss).`,
    `2. Rollback procedure that fits inside ${p.nonfunctional.rto}.`,
    `3. On-call rotation document and pager bindings.`,
    `4. Pre-launch checklist matching launch geography ${p.gtm.launchGeography || "(captured in GTM)"}.`,
    "```",
    ``,
    `## 8. Coding-agent house rules`,
    ``,
    `- Stop and ask if a requirement is ambiguous; do not invent acceptance criteria.`,
    `- Reference IDs (FR-/NFR-/FEAT-/ADR-/RISK-) when describing what you changed.`,
    `- Do not silence type errors with \`any\` or unchecked casts.`,
    `- Do not add backward-compatibility shims unless an explicit migration is in scope.`,
    `- Generate small commits per FEAT-ID; PR titles include the FEAT-ID.`,
  );
  return out.join("\n");
}

function stackSummary(p: Project): string {
  const pl = p.platform;
  return [
    `- Frontend: ${pl.frontend}${pl.uiFramework ? ` + ${pl.uiFramework}` : ""}`,
    `- State management: ${pl.stateMgmt}`,
    `- Backend: ${pl.backend} (${pl.apiStyle})`,
    `- Database: ${pl.database} (${pl.dataShape})`,
    `- Auth: ${pl.authMethod}${pl.rbacRequired ? " + RBAC" : ""}`,
    `- Cloud: ${pl.cloud}`,
    `- CI/CD: ${pl.cicd}`,
    `- Observability: ${pl.observability}`,
  ].join("\n");
}
