import { Project } from "../schema";
import { fallback, header } from "./util";

export function generateSystemDesign(p: Project): string {
  const v = p.systemDesign;
  const reqsPerDay = v.dau * v.avgRequestsPerUserPerDay;
  const reqsPerSec = reqsPerDay > 0 ? reqsPerDay / 86400 : 0;
  const peakRps = Math.max(reqsPerSec * 5, v.peakConcurrent);
  const storage12mo = v.dataGrowthGBPerMonth * 12;

  const out: string[] = [
    header(p, `System design — ${p.name || "Untitled"}`, "System design"),
    `## 1. Capacity estimates`,
    ``,
    `| Metric | Value |`,
    `|---|---|`,
    `| Total expected users (lifetime) | ${v.expectedUsersTotal.toLocaleString()} |`,
    `| DAU | ${v.dau.toLocaleString()} |`,
    `| MAU | ${v.mau.toLocaleString()} |`,
    `| Peak concurrent users | ${v.peakConcurrent.toLocaleString()} |`,
    `| Avg requests / user / day | ${v.avgRequestsPerUserPerDay.toLocaleString()} |`,
    `| Read / write ratio | ${v.readWriteRatio} |`,
    `| Notifications / day | ${v.notificationsPerDay.toLocaleString()} |`,
    `| Latency target (p95) | ${v.latencyTargetMs} ms |`,
    `| Availability target | ${v.availabilityTarget} |`,
    ``,
    `### Derived (back-of-envelope)`,
    ``,
    `- **Average requests/day:** ${reqsPerDay.toLocaleString()}`,
    `- **Average requests/sec:** ${reqsPerSec.toFixed(2)}`,
    `- **Estimated peak RPS:** ${peakRps.toFixed(2)} _(uses 5× sustained or peak-concurrent floor)_`,
    `- **Storage at 12 months:** ~${storage12mo.toLocaleString()} GB at current growth rate`,
    ``,
    `> Treat these as ranges, not contracts. Validate against synthetic load before launch.`,
    ``,
    `## 2. High-level architecture`,
    ``,
    `\`\`\``,
    `[Clients]`,
    `   │`,
    `   ▼`,
    `[CDN / Edge] ──► static assets`,
    `   │`,
    `   ▼`,
    `[API Gateway] ── auth, rate-limit, RBAC`,
    `   │`,
    `   ├──► [App services] (${p.platform.backend})`,
    `   │       │`,
    `   │       ├──► [Cache] (${v.cachingStrategy ? "see §4" : "Redis or equivalent"})`,
    `   │       ├──► [Primary DB] (${p.platform.database})`,
    `   │       └──► [Queue / events] (${v.queueStrategy ? "see §6" : "SQS / Kafka / equivalent"})`,
    `   │`,
    `   └──► [Object storage] for blobs and exports`,
    `\`\`\``,
    ``,
    `## 3. Data flow`,
    ``,
    `Typical write path:`,
    ``,
    `1. Client → CDN → API Gateway (auth, rate-limit, schema check).`,
    `2. App service validates, writes to primary DB inside a transaction.`,
    `3. App service emits an event onto the bus for downstream consumers.`,
    `4. Notification worker, analytics worker, search-indexer worker subscribe and act.`,
    ``,
    `Typical read path:`,
    ``,
    `1. Client → CDN cache for static; API Gateway for dynamic.`,
    `2. App service checks Redis hot-path cache; on miss, reads from DB and populates cache.`,
    `3. Response paths emit metrics to the observability stack for SLO tracking.`,
    ``,
    `## 4. Caching strategy`,
    ``,
    fallback(v.cachingStrategy, "Default: CDN edge for static assets, Redis for hot reads with explicit TTL and invalidation, query-result cache for expensive aggregates."),
    ``,
    `## 5. Database scaling strategy`,
    ``,
    fallback(v.dbScalingStrategy, "Default: vertical scale until read-replica threshold; then read replicas; then partition by tenant once a single tenant nears node limits. Archive cold data to object storage."),
    ``,
    `## 6. Queue & event strategy`,
    ``,
    fallback(v.queueStrategy, "Default: managed message bus for events with idempotent consumers, dead-letter queue with alerting, exponential backoff and retry budget."),
    ``,
    `## 7. Multi-region & DR`,
    ``,
    `- **Geographic coverage.** ${fallback(v.geographicCoverage)}`,
    `- **Multi-region.** ${v.multiRegion ? "Yes — active/passive minimum; active/active when cost and consistency allow." : "Single-region for now; revisit when latency or sovereignty demands change."}`,
    `- **DR plan.** ${v.drNeeded ? "Required. Drills run quarterly with documented RTO/RPO." : "Not required at this stage; align with NF RTO/RPO when activated."}`,
    `- **RTO / RPO.** ${p.nonfunctional.rto} / ${p.nonfunctional.rpo}`,
    ``,
    `## 8. Failure scenarios`,
    ``,
    `- **DB primary loss.** Promote replica; readers degrade to last cache; writers queued briefly.`,
    `- **Region outage.** Drain to alternate region (if multi-region) or accept downtime within SLO error budget.`,
    `- **Notification provider outage.** Queue notifications, retry with backoff, fall back to alternate channel where applicable.`,
    `- **Cache cluster loss.** Service degrades to direct DB reads; rate-limit aggressively to prevent stampede.`,
    `- **Third-party integration failure.** Circuit-break, return cached state, surface partial-availability message to users.`,
    ``,
    `## 9. Notes`,
    ``,
    fallback(v.notes),
  ];
  return out.join("\n");
}
