import { Project } from "../schema";
import {
  ARCHITECTURE_SCENARIOS,
  SECURITY_REVIEW_OPTIONS,
  architectureScenarioPriority,
  scenarioRecommendation,
} from "../architecture-scenarios";
import { fallback, header } from "./util";

function sentenceChoice(value?: string) {
  return fallback(value ? value.replace(/-/g, " ") : "");
}

function listOrFallback(items: string[], empty = "_None selected_") {
  return items.length === 0 ? empty : items.join(", ");
}

export function generateSystemDesign(p: Project): string {
  const v = p.systemDesign;
  const reqsPerDay = v.dau * v.avgRequestsPerUserPerDay;
  const reqsPerSec = reqsPerDay > 0 ? reqsPerDay / 86400 : 0;
  const peakRps = Math.max(reqsPerSec * 5, v.peakConcurrent);
  const storage12mo = v.dataGrowthGBPerMonth * 12;
  const architecturePattern = v.architecturePattern ?? "modular-monolith";
  const authArchitecture = v.authArchitecture ?? "managed-oidc";
  const deploymentTopology = v.deploymentTopology ?? (v.multiRegion ? "active-passive" : "single-region");
  const tradeoffAreas = v.tradeoffAreas ?? [];
  const securityReviewAreas = v.securityReviewAreas ?? [];
  const securityLabels = Object.fromEntries(SECURITY_REVIEW_OPTIONS.map((option) => [option.value, option.label]));
  const clients = p.experience.surfaces.length > 0 ? p.experience.surfaces.join(", ") : p.platform.kinds.join(", ") || "web / app clients";
  const integrations = p.dataTech.integrations.length > 0 ? p.dataTech.integrations.map((i) => i.system).join(", ") : "external systems";
  const aiNode = p.ai.needsAI ? `\n  app --> ai["AI / agent workflow: ${p.ai.agentFramework}"]\n  ai --> evals["Evals, guardrails, audit"]` : "";

  const out: string[] = [
    header(p, `Architecture blueprint — ${p.name || "Untitled"}`, "Architecture blueprint"),
    `## 1. Capacity estimates`,
    ``,
    `| Metric | Value |`,
    `|---|---|`,
    `| Total expected users (lifetime) | ${v.expectedUsersTotal.toLocaleString()} |`,
    `| DAU | ${v.dau.toLocaleString()} |`,
    `| MAU | ${v.mau.toLocaleString()} |`,
    `| Peak concurrent users | ${v.peakConcurrent.toLocaleString()} |`,
    `| Avg requests / user / day | ${v.avgRequestsPerUserPerDay.toLocaleString()} |`,
    `| Read / write ratio | ${v.readWriteRatio} |`,
    `| Notifications / day | ${v.notificationsPerDay.toLocaleString()} |`,
    `| Latency target (p95) | ${v.latencyTargetMs} ms |`,
    `| Availability target | ${v.availabilityTarget} |`,
    ``,
    `### Derived (back-of-envelope)`,
    ``,
    `- **Average requests/day:** ${reqsPerDay.toLocaleString()}`,
    `- **Average requests/sec:** ${reqsPerSec.toFixed(2)}`,
    `- **Estimated peak RPS:** ${peakRps.toFixed(2)} _(uses 5× sustained or peak-concurrent floor)_`,
    `- **Storage at 12 months:** ~${storage12mo.toLocaleString()} GB at current growth rate`,
    ``,
    `> Treat these as ranges, not contracts. Validate against synthetic load before launch.`,
    ``,
    `## 2. Architecture decisions at a glance`,
    ``,
    `| Decision | Current direction | Why it matters |`,
    `|---|---|---|`,
    `| Architecture pattern | ${sentenceChoice(architecturePattern)} | Controls team boundaries, deploy complexity, and coding-agent decomposition. |`,
    `| Auth architecture | ${sentenceChoice(authArchitecture)} | Covers OAuth/OIDC/SSO/session/API-key model and downstream authorization. |`,
    `| Deployment topology | ${sentenceChoice(deploymentTopology)} | Sets latency, residency, DR, and operating-cost expectations. |`,
    `| API style | ${p.platform.apiStyle} | Drives contract shape, SDK generation, and partner/coding-tool handoff. |`,
    `| Primary data store | ${p.platform.database} (${p.platform.dataShape}) | Defines transaction safety, querying, and migration path. |`,
    `| Deployment runtime | ${fallback(p.platform.deploymentRuntime, p.platform.cloud)} | Defines serverless/container/Kubernetes boundaries, worker placement, and operational ownership. |`,
    `| Network boundary | ${fallback(p.platform.networking)} | Makes private connectivity, WAF/load-balancing, egress, and tenant isolation explicit. |`,
    `| Build vs. buy | ${fallback(p.dataTech.buildVsBuy)} | Separates differentiated product logic from commodity platform capabilities. |`,
    ``,
    `### Enterprise platform inputs`,
    ``,
    `| Area | Direction |`,
    `|---|---|`,
    `| Managed cloud services | ${fallback(p.platform.cloudServices)} |`,
    `| Scaling approach | ${fallback(p.platform.scalingApproach)} |`,
    `| CI/CD release gates | ${fallback(p.platform.cicdDetails || p.platform.cicd)} |`,
    `| IaC and policy | ${fallback(p.platform.iacDetails || p.platform.iac)} |`,
    `| Enterprise controls | ${fallback(p.platform.enterpriseControls)} |`,
    ``,
    `## 3. High-level architecture`,
    ``,
    `This view is for product, engineering, security, and GTM stakeholders. It should answer: who uses it, what systems exist, what owns identity, where data lives, and where external dependencies sit.`,
    ``,
    `\`\`\`mermaid`,
    `flowchart LR`,
    `  users["Users / operators / admins"] --> clients["Clients: ${clients}"]`,
    `  clients --> edge["CDN / edge / WAF"]`,
    `  edge --> auth["Identity: ${p.platform.authMethod} (${sentenceChoice(authArchitecture)})"]`,
    `  edge --> api["API boundary: ${p.platform.apiStyle}"]`,
    `  api --> app["Application layer: ${sentenceChoice(architecturePattern)}"]`,
    `  app --> db["Primary data: ${p.platform.database}"]`,
    p.platform.caching || v.cachingStrategy ? `  app --> cache["Cache / hot path"]` : `  app -. optional .-> cache["Cache when measured"]`,
    p.platform.eventDriven || p.platform.backgroundJobs || v.queueStrategy ? `  app --> queue["Queues / events / workflows"]` : `  app -. optional .-> queue["Async jobs when needed"]`,
    `  app --> obs["Observability + audit"]`,
    `  app --> vendors["Integrations: ${integrations}"]${aiNode}`,
    `\`\`\``,
    ``,
    fallback(v.highLevelArchitectureNotes, "_No custom high-level notes captured._"),
    ``,
    `### C4-style context summary`,
    ``,
    `- **Product surface.** ${listOrFallback(p.platform.kinds, "_No platform kinds selected_")}`,
    `- **Primary users.** ${fallback(p.market.endUser || p.problem.audience)}`,
    `- **Operators/admins.** ${fallback(p.market.operator)}`,
    `- **Identity boundary.** ${p.platform.authRequired ? `${p.platform.authMethod} with ${p.platform.rbacRequired ? "RBAC" : "basic authorization"}` : "Public/no-auth paths allowed"}.`,
    `- **Data boundary.** ${p.platform.multiTenant ? "Multi-tenant data paths must be tenant-scoped." : "Single-tenant or tenanting not yet selected."}`,
    `- **Regulatory boundary.** ${p.compliance.frameworks.length > 0 ? p.compliance.frameworks.join(", ") : "_No frameworks selected yet_"}.`,
    ``,
    `## 4. Low-level architecture`,
    ``,
    `This view is for lead engineers and coding agents. It should answer: what modules exist, what each module owns, how requests move, where async work happens, and which contracts need tests.`,
    ``,
    `\`\`\`mermaid`,
    `flowchart TD`,
    `  client["Client app"] --> gateway["API gateway / route handlers"]`,
    `  gateway --> authz["AuthN/AuthZ middleware"]`,
    `  authz --> modules["Domain modules / services"]`,
    `  modules --> contracts["OpenAPI / schemas / validation"]`,
    `  modules --> primary["Primary DB: ${p.platform.database}"]`,
    `  modules --> audit["Audit log"]`,
    p.platform.caching || v.cachingStrategy ? `  modules --> cache["Cache: TTL + invalidation owner"]` : `  modules -.-> cache["Cache if load tests require it"]`,
    p.platform.backgroundJobs || p.platform.eventDriven || v.queueStrategy ? `  modules --> outbox["Outbox / event publisher"]\n  outbox --> workers["Workers / workflow consumers"]` : `  modules -.-> workers["Background workers when introduced"]`,
    `  workers --> vendors["External providers"]`,
    `  modules --> telemetry["Metrics / logs / traces"]`,
    p.ai.needsAI ? `  modules --> agent["AI agent boundary"]\n  agent --> guardrails["Schema, evals, policy checks"]` : `  modules -. future .-> agent["AI agent boundary"]`,
    `\`\`\``,
    ``,
    fallback(v.lowLevelArchitectureNotes, "_No custom low-level notes captured._"),
    ``,
    `### LLD specification inputs`,
    ``,
    `| Area | Architect input |`,
    `|---|---|`,
    `| Domain model and aggregates | ${fallback(v.domainModelNotes)} |`,
    `| Schema design and indexes | ${fallback(v.schemaDesignNotes)} |`,
    `| Data lifecycle and migration | ${fallback(v.dataLifecycleNotes)} |`,
    `| API contracts and versioning | ${fallback(v.apiContractNotes)} |`,
    `| Service and module boundaries | ${fallback(v.serviceBoundaryNotes)} |`,
    `| Workflow state machines | ${fallback(v.workflowStateNotes)} |`,
    `| Integration contracts and failure handling | ${fallback(v.integrationContractNotes)} |`,
    `| Security architecture | ${fallback(v.securityArchitectureNotes)} |`,
    `| Observability and SLO instrumentation | ${fallback(v.observabilityDesignNotes)} |`,
    `| Infrastructure and deployment architecture | ${fallback(v.infraArchitectureNotes)} |`,
    `| Test architecture and quality gates | ${fallback(v.testArchitectureNotes)} |`,
    ``,
    `### Coding-agent handoff rules`,
    ``,
    `- Generate code from module boundaries, not from page names alone.`,
    `- Every API path needs auth scope, input schema, response schema, idempotency behavior, and error states.`,
    `- Every entity needs owner module, retention rule, tenant scope, and test fixtures.`,
    `- Every async event needs producer, consumer, retry budget, dead-letter path, and replay command.`,
    `- Every security-sensitive flow needs a failing authorization test before implementation is considered done.`,
    ``,
    `## 5. Legacy box view`,
    ``,
    `This simplified view is retained for quick discussion when a Mermaid renderer is unavailable.`,
    ``,
    `\`\`\``,
    `[Clients]`,
    `   │`,
    `   ▼`,
    `[CDN / Edge] ──► static assets`,
    `   │`,
    `   ▼`,
    `[API Gateway] ── auth, rate-limit, RBAC`,
    `   │`,
    `   ├──► [App services] (${p.platform.backend})`,
    `   │       │`,
    `   │       ├──► [Cache] (${v.cachingStrategy ? "see §4" : "Redis or equivalent"})`,
    `   │       ├──► [Primary DB] (${p.platform.database})`,
    `   │       └──► [Queue / events] (${v.queueStrategy ? "see §6" : "SQS / Kafka / equivalent"})`,
    `   │`,
    `   └──► [Object storage] for blobs and exports`,
    `\`\`\``,
    ``,
    `## 6. Data flow`,
    ``,
    `Typical write path:`,
    ``,
    `1. Client → CDN → API Gateway (auth, rate-limit, schema check).`,
    `2. App service validates, writes to primary DB inside a transaction.`,
    `3. App service emits an event onto the bus for downstream consumers.`,
    `4. Notification worker, analytics worker, search-indexer worker subscribe and act.`,
    ``,
    `Typical read path:`,
    ``,
    `1. Client → CDN cache for static; API Gateway for dynamic.`,
    `2. App service checks Redis hot-path cache; on miss, reads from DB and populates cache.`,
    `3. Response paths emit metrics to the observability stack for SLO tracking.`,
    ``,
    `## 7. Enterprise infrastructure plan`,
    ``,
    `- **Runtime.** ${fallback(p.platform.deploymentRuntime, `${p.platform.cloud} / ${p.platform.containerization}`)}`,
    `- **Managed services.** ${fallback(p.platform.cloudServices)}`,
    `- **Network boundary.** ${fallback(p.platform.networking)}`,
    `- **Scaling approach.** ${fallback(p.platform.scalingApproach)}`,
    `- **CI/CD gates.** ${fallback(p.platform.cicdDetails || p.platform.cicd)}`,
    `- **IaC and policy.** ${fallback(p.platform.iacDetails || p.platform.iac)}`,
    `- **Enterprise controls.** ${fallback(p.platform.enterpriseControls)}`,
    ``,
    `## 8. Caching strategy`,
    ``,
    fallback(v.cachingStrategy, "Default: CDN edge for static assets, Redis for hot reads with explicit TTL and invalidation, query-result cache for expensive aggregates."),
    ``,
    `## 9. Database scaling strategy`,
    ``,
    fallback(v.dbScalingStrategy, "Default: vertical scale until read-replica threshold; then read replicas; then partition by tenant once a single tenant nears node limits. Archive cold data to object storage."),
    ``,
    `## 10. Queue & event strategy`,
    ``,
    fallback(v.queueStrategy, "Default: managed message bus for events with idempotent consumers, dead-letter queue with alerting, exponential backoff and retry budget."),
    ``,
    `## 11. Multi-region & DR`,
    ``,
    `- **Geographic coverage.** ${fallback(v.geographicCoverage)}`,
    `- **Deployment topology.** ${sentenceChoice(deploymentTopology)}.`,
    `- **Multi-region.** ${v.multiRegion ? "Yes — active/passive minimum; active/active when cost and consistency allow." : "Single-region for now; revisit when latency or sovereignty demands change."}`,
    `- **DR plan.** ${v.drNeeded ? "Required. Drills run quarterly with documented RTO/RPO." : "Not required at this stage; align with NF RTO/RPO when activated."}`,
    `- **RTO / RPO.** ${p.nonfunctional.rto} / ${p.nonfunctional.rpo}`,
    ``,
    `## 12. Technical tradeoff matrix`,
    ``,
    `Use this as the architecture review checklist. Items marked **Review now** are either selected in intake or inferred from the current product constraints.`,
    ``,
    `| Area | Priority | Options to consider | Recommendation |`,
    `|---|---|---|---|`,
    ...ARCHITECTURE_SCENARIOS.map((scenario) => {
      const priority = architectureScenarioPriority(p, scenario.id);
      const selected = tradeoffAreas.includes(scenario.id) ? "selected" : "inferred";
      return `| ${scenario.label} | ${priority}${priority === "Review now" ? ` (${selected})` : ""} | ${scenario.options.join("<br>")} | ${scenarioRecommendation(p, scenario.id)} |`;
    }),
    ``,
    `### Security review focus`,
    ``,
    securityReviewAreas.length === 0
      ? "_No security review areas selected. Minimum recommendation: identity, authorization, data protection, secrets, audit, and incident response._"
      : securityReviewAreas.map((area) => `- ${securityLabels[area] ?? area}`).join("\n"),
    ``,
    `## 13. Failure scenarios`,
    ``,
    `- **DB primary loss.** Promote replica; readers degrade to last cache; writers queued briefly.`,
    `- **Region outage.** Drain to alternate region (if multi-region) or accept downtime within SLO error budget.`,
    `- **Notification provider outage.** Queue notifications, retry with backoff, fall back to alternate channel where applicable.`,
    `- **Cache cluster loss.** Service degrades to direct DB reads; rate-limit aggressively to prevent stampede.`,
    `- **Third-party integration failure.** Circuit-break, return cached state, surface partial-availability message to users.`,
    ``,
    `## 14. DeepAgents-ready generation path`,
    ``,
    `If the product later adds AI-generated architecture narratives, diagrams, or PM-ready handoff content, use a server-side DeepAgents/LangGraph worker rather than running LLM orchestration in the browser.`,
    ``,
    `Recommended workspace:`,
    ``,
    `\`\`\``,
    `architecture-agent/`,
    `├── AGENTS.md                  # product voice, architecture standards, output style`,
    `├── skills/`,
    `│   ├── architecture-blueprint/SKILL.md`,
    `│   ├── tradeoff-review/SKILL.md`,
    `│   ├── diagram-generation/SKILL.md`,
    `│   └── coding-handoff/SKILL.md`,
    `├── subagents.yaml             # security reviewer, platform architect, PM editor`,
    `└── content_writer.py           # server/CLI runner with tools and filesystem backend`,
    `\`\`\``,
    ``,
    `Guardrails for this repo:`,
    ``,
    `- Keep deterministic artifacts as the baseline so the app works without API keys.`,
    `- Run DeepAgents only in a backend job/CLI with explicit environment variables and review before publishing.`,
    `- Save generated diagrams/content back into artifacts only after schema validation and human approval.`,
    `- Use subagents for security review, platform review, and PM editing, not for unbounded implementation.`,
    ``,
    `## 15. Big-tech / startup product review lens`,
    ``,
    `- **PM sign-off.** The architecture explains customer impact, MVP scope, failure modes, launch gates, and tradeoffs in business language.`,
    `- **Engineering sign-off.** The low-level view identifies module ownership, data ownership, contracts, queues, caches, and observability.`,
    `- **Security sign-off.** Identity, OAuth/SSO, authorization, data protection, audit, incident response, and compliance controls are explicit.`,
    `- **Startup practicality.** Defaults avoid premature microservices and keep commodity capabilities bought unless they are the product moat.`,
    `- **Coding-tool readiness.** Cursor/Codex-style agents get stable files, schemas, APIs, acceptance tests, ADRs, and guardrails before writing code.`,
    ``,
    `## 16. Notes`,
    ``,
    fallback(v.notes),
  ];
  return out.join("\n");
}
