import type { Project } from "../schema";
import { ALL_COMPLETE, TemplateMeta } from "./types";

const payload: Partial<Project> = {
  name: "Internal operations console",
  oneLiner:
    "An internal web console that consolidates manual operator workflows behind RBAC + audit logging — replaces five spreadsheets and three side-tools.",
  ideaDescription:
    "We're building an internal operations console for our customer-operations team. Today they juggle Salesforce, three internal admin pages, two spreadsheets, and direct database queries to run their day. The console consolidates the top 10 daily workflows (account search, plan changes, refund processing, exception handling, audit review) behind RBAC, audit logging, and an approval workflow for sensitive actions. Internal-only — adoption matters more than polish.",
  problem: {
    problem:
      "Ops team spends 30-40% of the day stitching tools and copy-pasting between systems. Errors are easy; auditing is impossible. Sensitive actions (refunds, plan changes) lack approval gates.",
    audience: "Internal customer-operations team (~25 FTE) and their leads.",
    whyNow:
      "Recent incident: a manual SQL update affected 1200 customers due to a typo. SOC 2 audit prep requires audit logging for sensitive changes. Hiring is frozen — productivity has to come from tools.",
    successCriteria:
      "Reduce avg time-per-task on top 10 workflows by 40%. 100% of sensitive actions go through approval workflow. Zero unaudited writes to customer records.",
    outOfScope:
      "Customer-facing surfaces; analytics deep-dives (Looker handles that); ML-based anomaly detection in v1.",
    businessCase:
      "Saving 30% of 25 ops FTE = ~$1.5M/yr in capacity that doesn't need to be hired. Plus risk reduction on audited changes.",
    priority: "P1",
  },
  market: {
    buyer: "VP Customer Operations",
    endUser: "Customer ops agents and team leads",
    operator: "Platform / internal-tools eng team",
    alternatives: "Status quo (Salesforce + spreadsheets + Retool patches); Retool full build.",
    differentiation: "Owned in-house with full RBAC + audit; integrated with our domain model.",
    marketSize: "Internal — N/A (no external sale).",
    pricing: "Internal capability.",
    geo: ["canada"],
    vertical: "saas-internal",
  },
  experience: {
    surfaces: ["internal-console"],
    authMode: "authenticated",
    primaryDevice: "desktop-first",
    offline: false,
    localization: "en-CA",
    accessibility: "WCAG 2.2 AA (internal users with assistive tech)",
    notifications: ["email", "in-app"],
    timingModel: "neither",
  },
  platform: {
    kinds: ["website", "internal-tool", "admin-dashboard"],
    webMarketing: false,
    webPortal: false,
    webAdmin: true,
    webPwa: false,
    webEnterprise: true,
    mobileIOS: false,
    mobileAndroid: false,
    mobileFramework: "none",
    frontend: "react",
    uiFramework: "shadcn/ui + Tailwind",
    stateMgmt: "TanStack Query",
    designSystem: "Internal-tools-functional",
    authRequired: true,
    responsiveRequired: false,
    accessibilityRequired: true,
    backend: "django",
    apiStyle: "rest",
    authMethod: "oidc",
    rbacRequired: true,
    backgroundJobs: true,
    webhooks: false,
    eventDriven: false,
    rateLimiting: false,
    caching: false,
    database: "postgres",
    dataShape: "structured",
    multiTenant: false,
    searchNeeded: true,
    realtimeNeeded: false,
    cloud: "aws",
    cicd: "GitHub Actions",
    iac: "Terraform",
    observability: "OpenTelemetry + Datadog",
    containerization: "docker",
    envStrategy: "dev / stage / prod",
  },
  functional: {
    personas: [
      { id: "p1", name: "Ops agent", jtbd: "Resolve customer requests fast and correctly.", pains: "Tab-juggling; risky direct-to-DB workarounds.", channel: "internal-console" },
      { id: "p2", name: "Ops team lead", jtbd: "Approve sensitive actions; review activity; coach the team.", pains: "No visibility into what was changed.", channel: "internal-console" },
      { id: "p3", name: "Compliance owner", jtbd: "Prove audit trail for sensitive changes.", pains: "Stitching audit evidence across systems for SOC 2.", channel: "internal-console" },
      { id: "p4", name: "Platform engineer", jtbd: "Ship safe ops capabilities without rebuilding the same RBAC + audit layer every time.", pains: "Each new tool re-implements primitives.", channel: "internal-console" },
    ],
    requirements: [
      { id: "FR-001", kind: "functional", title: "Account search", description: "Fast search across customers by id, email, domain, plan, status.", acceptance: "Sub-second p95 across 5M records.", priority: "must" },
      { id: "FR-002", kind: "functional", title: "Account 360 view", description: "Single-page view: profile, plan, billing, recent activity, tickets.", acceptance: "Renders in < 2s; lazy loads heavy modules.", priority: "must" },
      { id: "FR-003", kind: "functional", title: "Plan change with approval", description: "Agent initiates plan change; lead approves; system applies + audits.", acceptance: "Approval state machine; cannot apply without sign-off.", priority: "must" },
      { id: "FR-004", kind: "functional", title: "Refund processing with approval", description: "Refund up to threshold by agent; above threshold requires lead approval.", acceptance: "Threshold configurable; audit log captures both submitter + approver.", priority: "must" },
      { id: "FR-005", kind: "functional", title: "Exception handling queue", description: "Failed billing / sync exceptions surfaced for triage.", acceptance: "Queue refreshes every 5min; bulk-action with confirm.", priority: "should" },
      { id: "FR-006", kind: "functional", title: "Audit log explorer", description: "Browse audit events with filter by actor, target, action, time.", acceptance: "All sensitive writes appear within 30s; 13mo retention default.", priority: "must" },
      { id: "FR-007", kind: "functional", title: "Role-based access control", description: "Roles: viewer, agent, lead, ops-engineer, compliance-reader.", acceptance: "Permission changes effective in < 5s; SCIM-driven role mapping.", priority: "must" },
      { id: "NFR-001", kind: "nonfunctional", title: "Audit completeness", description: "Every sensitive write produces an audit event.", acceptance: "Pen + audit test confirms 100% coverage of declared sensitive actions.", priority: "must" },
      { id: "NFR-002", kind: "nonfunctional", title: "Internal SSO required", description: "Google Workspace SSO with group-mapped roles.", acceptance: "No password login path; group changes effective < 5s.", priority: "must" },
    ],
    features: [
      { id: "FEAT-001", name: "SSO + role provisioning", description: "Google Workspace OIDC + SCIM; map groups to roles.", userStory: "As an admin, I provision via Google Group changes alone.", acceptance: "Role change effective < 5s.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Google Workspace", apisNeeded: "/auth/*", dataNeeded: "User, Role", edgeCases: "Group rename; user offboarded mid-task", errorStates: "Lock session; redirect to logout", adminControls: "Force-logout; revoke", audit: "Auth events", security: "Hardware-key MFA", futureEnhancements: "Just-in-time access requests", release: "mvp" },
      { id: "FEAT-002", name: "Account search", description: "Full-text + structured search across customers.", userStory: "As an agent, I find an account in <10s.", acceptance: "p95 < 1s on 5M records.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Search index", apisNeeded: "/search", dataNeeded: "AccountIndex", edgeCases: "Sparse fields; fuzzy email lookup", errorStates: "Empty-state with hint", adminControls: "Reindex", audit: "Search history per user", security: "RBAC-scoped", futureEnhancements: "Saved-search shortcuts", release: "mvp" },
      { id: "FEAT-003", name: "Account 360", description: "Single-page view consolidating profile, plan, billing, activity, tickets.", userStory: "As an agent, I see everything I need in one place.", acceptance: "Renders < 2s; lazy modules.", priority: "must", complexity: "L", businessValue: "high", dependencies: "Internal APIs (CRM, billing, support)", apisNeeded: "/accounts/{id}/*", dataNeeded: "Account, Plan, Activity", edgeCases: "Slow upstream API; broken FK", errorStates: "Per-module error boundary", adminControls: "Configure visible modules per role", audit: "Access logged", security: "RBAC-scoped", futureEnhancements: "Inline timeline annotations", release: "mvp" },
      { id: "FEAT-004", name: "Approval workflow framework", description: "Generic submit → review → apply state machine reusable across plan-change, refund, etc.", userStory: "As a platform eng, I add a new approvable action without rebuilding the workflow.", acceptance: "Adding a new action requires < 1 day of eng work.", priority: "must", complexity: "L", businessValue: "high", dependencies: "—", apisNeeded: "/approvals/*", dataNeeded: "Approval", edgeCases: "Approver rotation mid-flight; auto-expiry", errorStates: "Approval expired → resubmit", adminControls: "Per-action threshold + approver group", audit: "Every state change", security: "Approver cannot be submitter", futureEnhancements: "Multi-stage approvals", release: "mvp" },
      { id: "FEAT-005", name: "Plan change", description: "Initiate + approve + apply plan change.", userStory: "As an agent, I request a plan change with approval gate.", acceptance: "Cannot apply without approval.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Billing API, Approvals", apisNeeded: "—", dataNeeded: "PlanChange", edgeCases: "Customer mid-billing-cycle; downgrade with credit", errorStates: "Show prorated impact pre-apply", adminControls: "Per-tier approver mapping", audit: "Submit + approve + apply events", security: "RBAC", futureEnhancements: "Bulk plan migrations", release: "mvp" },
      { id: "FEAT-006", name: "Refund processing", description: "Refund up to threshold by agent; above by lead.", userStory: "As an agent, I process refunds within my threshold; escalate above.", acceptance: "Threshold configurable per role.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Billing API, Approvals", apisNeeded: "—", dataNeeded: "Refund", edgeCases: "Partial refund; refund + reversal", errorStates: "Surface payment failure clearly", adminControls: "Threshold per role per region", audit: "Submit + approve + execution events", security: "Approver cannot be submitter", futureEnhancements: "Auto-suggested refund based on policy", release: "mvp" },
      { id: "FEAT-007", name: "Exception handling queue", description: "Failed billing / sync exceptions in a triage queue.", userStory: "As a lead, I clear exceptions before customers feel them.", acceptance: "Queue refresh every 5min; bulk-action.", priority: "should", complexity: "M", businessValue: "medium", dependencies: "Internal billing webhooks", apisNeeded: "/exceptions/*", dataNeeded: "Exception", edgeCases: "Bulk-action mistakes", errorStates: "Undo within 5 min", adminControls: "Queue assignment rules", audit: "Per-exception log", security: "RBAC", futureEnhancements: "ML-prioritized triage", release: "v1" },
      { id: "FEAT-008", name: "Audit log explorer", description: "Browse audit events with filters; export.", userStory: "As compliance, I export evidence for SOC 2 audit.", acceptance: "All sensitive writes appear in <30s; CSV/JSONL export.", priority: "must", complexity: "M", businessValue: "high", dependencies: "—", apisNeeded: "/audit/*", dataNeeded: "AuditEvent", edgeCases: "Large export; subject access request", errorStates: "Stream to file; resume on disconnect", adminControls: "Retention per category", audit: "Read access logged", security: "Compliance role only", futureEnhancements: "SIEM streaming", release: "mvp" },
      { id: "FEAT-009", name: "Action-runner framework", description: "Library of typed actions (refund, plan-change, exception-resolve) the console exposes uniformly.", userStory: "As a platform eng, I add a new ops action with consistent UX, RBAC, audit.", acceptance: "New action ships in <1 day eng.", priority: "should", complexity: "L", businessValue: "high", dependencies: "—", apisNeeded: "/actions/*", dataNeeded: "ActionDefinition", edgeCases: "—", errorStates: "—", adminControls: "Action visibility per role", audit: "Every invocation", security: "RBAC", futureEnhancements: "Self-serve action proposal flow for ops leads", release: "v1" },
    ],
    kpis: [
      { id: "KPI-001", name: "Avg time per task", definition: "Median minutes for top-10 tasks before vs. after console", target: "-40% on baseline", cadence: "monthly" },
      { id: "KPI-002", name: "Audit coverage", definition: "% of sensitive writes captured in audit log", target: "100%", cadence: "weekly" },
      { id: "KPI-003", name: "Approval rate adherence", definition: "% of above-threshold actions with documented approval", target: "100%", cadence: "weekly" },
      { id: "KPI-004", name: "Adoption", definition: "% of weekly active ops agents using console (vs. legacy tools)", target: ">= 95% by month 3", cadence: "weekly" },
    ],
    businessRules:
      "Above-threshold actions require approval from someone other than the submitter. All sensitive writes are audited. Read access to PII is also logged. SSO via Google Workspace; no password fallback.",
    edgeCases:
      "Approver offboarded mid-flight; bulk-action mistakes; cross-region plan changes; downgrade with credit; refund + reversal; SCIM group rename; offboarded user with active sessions.",
  },
  nonfunctional: {
    availabilityTarget: "99.5% (internal)",
    rto: "4 hours",
    rpo: "1 hour",
    performance: "Account search p95 < 1s; account 360 < 2s",
    privacyPosture: "PII visibility scoped by role; reads of PII are logged.",
    auditability: "Every sensitive write + read of PII captured in append-only log retained 13 months default; longer for compliance.",
    costBoundary: "Modest; internal capability.",
    supportModel: "Internal — platform team owns; on-call rotation.",
    slos: [
      { id: "SLO-001", surface: "Account search", metric: "p95 latency", target: "< 1s on 5M records" },
      { id: "SLO-002", surface: "Account 360", metric: "p95 render", target: "< 2s" },
      { id: "SLO-003", surface: "Audit completeness", metric: "% sensitive writes audited", target: "100%" },
      { id: "SLO-004", surface: "Approval workflow", metric: "submit → applied latency p95", target: "< 5 min after approval" },
    ],
  },
  dataTech: {
    entities: [
      { id: "ENT-001", name: "User (internal)", description: "Internal user identified by Google Workspace.", sensitive: true, retention: "While active + 90d" },
      { id: "ENT-002", name: "Role / Permission", description: "RBAC primitives.", sensitive: false, retention: "Indefinite" },
      { id: "ENT-003", name: "Approval", description: "Submit → review → apply state machine record.", sensitive: false, retention: "13 months" },
      { id: "ENT-004", name: "AuditEvent", description: "Append-only log of writes + sensitive reads.", sensitive: true, retention: "13 months default" },
      { id: "ENT-005", name: "ActionDefinition", description: "Schema for a typed action exposed by the console.", sensitive: false, retention: "Indefinite" },
    ],
    integrations: [
      { id: "INT-001", system: "Google Workspace", direction: "bidirectional", protocol: "OIDC + SCIM", dataClass: "Identity + group membership", notes: "SSO + role provisioning." },
      { id: "INT-002", system: "Internal Billing API", direction: "outbound", protocol: "REST", dataClass: "Customer + financial", notes: "Plan changes + refunds." },
      { id: "INT-003", system: "Internal CRM", direction: "outbound", protocol: "REST", dataClass: "Customer", notes: "Account 360 read source." },
      { id: "INT-004", system: "Internal Support", direction: "outbound", protocol: "REST", dataClass: "Ticket", notes: "Account 360 read source." },
      { id: "INT-005", system: "Datadog", direction: "outbound", protocol: "OTLP/HTTPS", dataClass: "Metrics + traces", notes: "Observability." },
    ],
    dataResidency: "ca-central-1 (internal Canadian deployment).",
    buildVsBuy: "Buy: identity (Google Workspace), observability. Build: console UI + approval framework + action runner + audit explorer.",
  },
  systemDesign: {
    expectedUsersTotal: 50,
    dau: 25,
    mau: 30,
    peakConcurrent: 25,
    avgRequestsPerUserPerDay: 200,
    readWriteRatio: "70:30",
    dataGrowthGBPerMonth: 5,
    notificationsPerDay: 200,
    availabilityTarget: "99.5%",
    latencyTargetMs: 1_000,
    geographicCoverage: "Canada (single region)",
    multiRegion: false,
    drNeeded: false,
    cachingStrategy: "Short-TTL cache for account 360 module fetches.",
    dbScalingStrategy: "Single Postgres primary + read replica is sufficient.",
    queueStrategy: "Background jobs for async actions (refund execution, exports).",
    notes: "Internal scale is small; the engineering work is RBAC + audit + workflow framework, not raw throughput.",
  },
  ai: {
    needsAI: false,
    kinds: [],
    ragNeeded: false,
    dataSources: "",
    modelProvider: "tbd",
    agentFramework: "none",
    observability: "none",
    vectorDb: "none",
    humanInLoop: false,
    guardrails: false,
    evaluation: false,
    promptManagement: false,
    auditLogs: false,
    privacyFiltering: false,
    notes: "AI candidates (auto-summarize tickets, suggest next-best-action) deferred to v2.",
  },
  compliance: {
    processesPersonalData: true,
    processesFinancialData: true,
    processesHealthData: false,
    frameworks: ["SOC2", "PIPEDA", "OWASP-ASVS"],
    consentMgmt: false,
    auditLogs: true,
    encryptionAtRest: true,
    encryptionInTransit: true,
    rbacRequired: true,
    dataResidencyRequired: true,
    incidentResponseRequired: true,
    pentestCadence: "annual",
    threatModel:
      "Top threats: insider abuse of elevated permissions, audit-log tampering, accidental bulk action errors. Mitigations: approval workflow; immutable audit log; bulk-action confirmations + undo windows.",
  },
  gtm: {
    packaging: "internal-only",
    segments: "Internal — customer ops team.",
    buyerObjections: "\"Why not buy Retool?\" — answered by domain integration depth + audit primitives we'd have to add anyway.",
    salesMotion: "Internal change management; team-by-team onboarding.",
    channelStrategy: "—",
    launchGeography: "Internal Canada.",
    complianceGating: "SOC 2 audit alignment; PIPEDA audit trail.",
    pricingModel: "Internal capability.",
    acquisitionChannels: "—",
    retentionStrategy: "Adoption metrics + monthly office hours with ops team.",
    partnerships: "—",
    competitors: "Retool, Forest Admin, in-house Django admin extensions.",
    positioning: "Internal-only — focus on adoption and SOC 2 readiness, not external positioning.",
    marketingKpis: "—",
  },
  governance: {
    owner: "Director of Internal Tools",
    approvers: "VP Customer Operations, Head of Compliance, VP Engineering",
    dependencies: "Internal Billing / CRM / Support API maintainers; Google Workspace admin team.",
    thirdParties: "Google Workspace, AWS, Datadog, GitHub.",
    legalReviews: "PIPEDA audit trail review; internal data-handling policy review.",
    procurementReviews: "—",
    unvalidatedAssumptions: "Ops team will adopt over Retool patches; approval workflow latency is acceptable.",
    decisionConfidence: "high",
  },
  stakeholders: [
    { id: "s1", role: "Director of Internal Tools", responsibility: "Ship the console + roadmap" },
    { id: "s2", role: "VP Customer Operations", responsibility: "Adoption + workflow definition" },
    { id: "s3", role: "Head of Compliance", responsibility: "SOC 2 alignment; audit trail review" },
    { id: "s4", role: "VP Engineering", responsibility: "Platform standards + on-call" },
  ],
  decisions: [
    { id: "ADR-001", title: "Build over Retool", context: "Domain integration depth + RBAC + audit primitives + SOC 2 alignment.", decision: "Build in-house on Django + React.", alternatives: "Retool with custom resources; Forest Admin.", consequences: "Higher initial eng cost; full ownership of primitives we'd build anyway.", status: "accepted", confidence: "high" },
    { id: "ADR-002", title: "Approval workflow as a generic framework", context: "Many actions need approval; don't reimplement.", decision: "Generic submit → review → apply state machine reusable across actions.", alternatives: "Per-action ad-hoc approvals.", consequences: "More upfront design; consistent UX + audit.", status: "accepted", confidence: "high" },
    { id: "ADR-003", title: "Google Workspace SSO + SCIM (no password)", context: "Internal-only; all employees on Google.", decision: "OIDC + SCIM only; no password fallback.", alternatives: "Local password fallback for break-glass.", consequences: "Simple identity story; depends on Google Workspace availability.", status: "accepted", confidence: "high" },
  ],
  risks: [
    { id: "RISK-001", description: "Adoption drag — agents resist new tool, keep using spreadsheets.", likelihood: "medium", impact: "high", mitigation: "Ops VP-mandated cutover; office hours; per-workflow champion; legacy tool removal once adoption > 90%." },
    { id: "RISK-002", description: "Approval workflow is too slow for high-volume actions.", likelihood: "medium", impact: "medium", mitigation: "Per-role threshold tuning; bulk-approve for repeated patterns; adjust quarterly." },
    { id: "RISK-003", description: "Audit log volume blows past retention budget.", likelihood: "low", impact: "low", mitigation: "Compress + tier old logs to S3; define retention per category." },
  ],
  assumptions: [
    { id: "ASM-001", text: "Ops VP can mandate cutover from spreadsheets in 90 days.", validated: true },
    { id: "ASM-002", text: "Approval framework will cover 80% of sensitive actions in v1.", validated: false },
  ],
  openQuestions: [
    { id: "Q-001", text: "Do we ship the action-runner framework in v1 or v1.1?", owner: "Director of Internal Tools" },
    { id: "Q-002", text: "Per-action threshold defaults — do we centralize or let ops VP set per region?", owner: "VP Customer Operations" },
  ],
  progress: ALL_COMPLETE,
};

export const INTERNAL_CONSOLE_TEMPLATE: TemplateMeta = {
  id: "internal-console",
  title: "Internal operations console",
  blurb:
    "RBAC + audit-logged console replacing five spreadsheets and three side-tools. Approval workflows for sensitive actions.",
  vertical: "Internal tooling",
  stackChips: ["React", "Django", "Postgres", "AWS"],
  complianceChips: ["SOC 2", "PIPEDA"],
  scaleChip: "Internal · 25 ops users · audit-first",
  payload,
};
