import type { Project } from "../schema";
import { ALL_COMPLETE, TemplateMeta } from "./types";

const payload: Partial<Project> = {
  name: "B2B SaaS analytics dashboard",
  oneLiner:
    "Multi-tenant analytics platform for SaaS product teams: ingest events, model funnels and cohorts, ship dashboards.",
  ideaDescription:
    "We're building a self-serve analytics product for SaaS product teams. Customers send events via SDKs (web, mobile, server) or warehouse syncs. Out of the box: funnels, retention cohorts, segmentation, and dashboards. Power users go deeper with SQL on top of a managed columnar store. Multi-tenant from day 1; SOC 2 + GDPR-ready before GA.",
  problem: {
    problem:
      "Product teams either run with no analytics, or stitch GA + warehouse + ad-hoc SQL — slow, brittle, and inconsistent across teams. Established tools (Amplitude, Mixpanel) are expensive and lock teams in.",
    audience: "Heads of Product, Product Analysts, Growth PMs at mid-market B2B SaaS companies.",
    whyNow:
      "Columnar OLAP (ClickHouse, DuckDB) is now operationally viable; warehouse-native analytics is mature; buyers want first-party data control without paying premium for hosted tools.",
    successCriteria:
      "Time-to-first-funnel < 1 day for new customers; >= 70% of paid customers ship a dashboard in week 1; gross retention >= 95%.",
    outOfScope:
      "Marketing attribution; customer-data-platform write-back to ad networks; mobile SDK in-app messaging.",
    businessCase:
      "Mid-market product teams spend $30-80K/yr on Amplitude or Mixpanel and want to consolidate. Our $25K ACV undercuts the incumbent and adds warehouse-native sync.",
    priority: "P1",
  },
  market: {
    buyer: "Head of Product / VP Product",
    endUser: "Product analysts, PMs, growth/data teams",
    operator: "Data engineering / platform team running the integration",
    alternatives: "Amplitude, Mixpanel, Heap, PostHog, in-house ClickHouse + Metabase setups.",
    differentiation:
      "Warehouse-native (Snowflake / BigQuery / Redshift) sync from day 1; transparent SQL escape hatch; SOC 2 + GDPR-ready; simpler pricing than incumbents.",
    marketSize:
      "~50K mid-market SaaS companies in NA + EU. SAM ~$2B/yr at average ACV of $30K.",
    pricing: "Per-MAU tiered + platform. $1K/mo platform + $0.10 per MTU above 100K.",
    geo: ["united-states", "canada", "european-union", "united-kingdom"],
    vertical: "saas-internal",
  },
  experience: {
    surfaces: ["public-website", "saas-platform", "internal-console", "api-only"] as Project["experience"]["surfaces"],
    authMode: "authenticated",
    primaryDevice: "desktop-first",
    offline: false,
    localization: "en-US (v1); de-DE, fr-FR in v2",
    accessibility: "WCAG 2.2 AA",
    notifications: ["email", "in-app", "slack"],
    timingModel: "neither",
  },
  platform: {
    kinds: ["website", "saas-platform", "admin-dashboard", "customer-portal"],
    webMarketing: true,
    webPortal: true,
    webAdmin: true,
    webPwa: false,
    webEnterprise: true,
    mobileIOS: false,
    mobileAndroid: false,
    mobileFramework: "none",
    frontend: "nextjs",
    uiFramework: "shadcn/ui + Tailwind",
    stateMgmt: "Zustand + TanStack Query",
    designSystem: "Linear-inspired neutral",
    authRequired: true,
    responsiveRequired: true,
    accessibilityRequired: true,
    backend: "nestjs",
    apiStyle: "rest",
    authMethod: "oidc",
    rbacRequired: true,
    backgroundJobs: true,
    webhooks: true,
    eventDriven: true,
    rateLimiting: true,
    caching: true,
    database: "postgres",
    dataShape: "mixed",
    multiTenant: true,
    searchNeeded: true,
    realtimeNeeded: false,
    cloud: "aws",
    cicd: "GitHub Actions",
    iac: "Terraform",
    observability: "OpenTelemetry + Datadog",
    containerization: "docker",
    envStrategy: "dev / stage / prod with PR previews",
  },
  functional: {
    personas: [
      { id: "p1", name: "Product analyst", jtbd: "Build funnels and cohort analyses without bothering data eng.", pains: "Existing tools too rigid; warehouse SQL too slow for self-serve.", channel: "internal-console" },
      { id: "p2", name: "Growth PM", jtbd: "See activation + retention by cohort and ship dashboards to standups.", pains: "Inconsistent metrics across teams; no easy way to share dashboards.", channel: "internal-console" },
      { id: "p3", name: "Data engineer", jtbd: "Sync events from warehouse without rebuilding pipelines.", pains: "Hosted tools force me to double-instrument or maintain reverse ETL.", channel: "internal-console" },
      { id: "p4", name: "VP Product", jtbd: "Trust one source of truth across product, growth, and CS.", pains: "Three teams report three numbers for the same metric.", channel: "internal-console" },
    ],
    requirements: [
      { id: "FR-001", kind: "functional", title: "Event ingestion (SDK)", description: "Web + server + mobile SDKs ingest events with minimal config.", acceptance: "First event from JS SDK to dashboard in < 5 min.", priority: "must" },
      { id: "FR-002", kind: "functional", title: "Warehouse-native sync", description: "Pull events from Snowflake / BigQuery / Redshift with schema mapping.", acceptance: "Sync configured + first event ingested in < 30 min.", priority: "must" },
      { id: "FR-003", kind: "functional", title: "Funnel builder", description: "Drag-drop funnel with conversion + drop-off + segment breakdown.", acceptance: "Funnel of 6 steps over 30d cohort renders in < 5s.", priority: "must" },
      { id: "FR-004", kind: "functional", title: "Retention cohorts", description: "Cohort-by-event with rolling, classic, and N-day retention views.", acceptance: "Cohort table for 90d / 12 weeks renders in < 10s.", priority: "must" },
      { id: "FR-005", kind: "functional", title: "SQL escape hatch", description: "Read-only SQL editor over the columnar store with autocomplete.", acceptance: "Query timeout configurable; results exportable as CSV.", priority: "should" },
      { id: "FR-006", kind: "functional", title: "Dashboards + sharing", description: "Compose charts into dashboards, share with team, schedule snapshots.", acceptance: "Dashboard share link with auth respects RBAC.", priority: "must" },
      { id: "FR-007", kind: "functional", title: "Slack + email digests", description: "Schedule dashboard snapshots into Slack channels or email.", acceptance: "Recurring digest delivered within 5 min of scheduled time.", priority: "should" },
      { id: "NFR-001", kind: "nonfunctional", title: "Multi-tenant isolation", description: "Tenant data is logically + cryptographically isolated.", acceptance: "Pen test confirms no cross-tenant read paths; per-tenant encryption keys.", priority: "must" },
      { id: "NFR-002", kind: "nonfunctional", title: "Query latency", description: "Median funnel/cohort query < 5s on 100M events.", acceptance: "Synthetic load test sustains target with < 5% P95 regression.", priority: "must" },
    ],
    features: [
      { id: "FEAT-001", name: "JS SDK", description: "Browser SDK with auto-track + manual events.", userStory: "As a developer, I add the SDK and start sending events in minutes.", acceptance: "First event ingested within 5 min of install.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Ingestion API", apisNeeded: "POST /events", dataNeeded: "Event", edgeCases: "Ad blockers; offline buffer", errorStates: "Retry with backoff; drop after 24h", adminControls: "Per-tenant API key rotation", audit: "—", security: "Origin allowlist", futureEnhancements: "Auto-PII detection on event properties", release: "mvp" },
      { id: "FEAT-002", name: "Server SDK (Node, Python, Go)", description: "Server-side event ingestion.", userStory: "As a backend dev, I send events from my server.", acceptance: "Event ingested with full request context.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Ingestion API", apisNeeded: "POST /events", dataNeeded: "Event", edgeCases: "Bulk batches; idempotency", errorStates: "Idempotent retry on 5xx", adminControls: "Per-key rate limit", audit: "—", security: "API key per environment", futureEnhancements: "—", release: "mvp" },
      { id: "FEAT-003", name: "Warehouse sync", description: "Snowflake / BigQuery / Redshift event pull with schema mapping.", userStory: "As a data engineer, I sync from my warehouse without re-instrumenting.", acceptance: "Sync configured + first event in < 30 min.", priority: "must", complexity: "L", businessValue: "high", dependencies: "Connector framework", apisNeeded: "/connectors/*", dataNeeded: "ConnectorConfig", edgeCases: "Schema drift; large historical backfill", errorStates: "Pause sync + alert on schema breaking change", adminControls: "Manual sync trigger; pause / resume", audit: "Connector run log", security: "Per-tenant warehouse creds", futureEnhancements: "Reverse ETL out (CDP-like)", release: "mvp" },
      { id: "FEAT-004", name: "Funnel builder", description: "Drag-drop funnel with conversion + drop-off + segments.", userStory: "As a PM, I build a funnel without writing SQL.", acceptance: "6-step funnel on 30d cohort < 5s.", priority: "must", complexity: "L", businessValue: "high", dependencies: "Query engine", apisNeeded: "/queries/funnel", dataNeeded: "FunnelDefinition", edgeCases: "Step with zero matches; tenant with sparse data", errorStates: "Empty-state with onboarding", adminControls: "—", audit: "Query history per user", security: "Tenant-scoped", futureEnhancements: "Path analysis in v2", release: "mvp" },
      { id: "FEAT-005", name: "Retention cohorts", description: "Classic + rolling + N-day retention.", userStory: "As a PM, I see week-N retention by acquisition cohort.", acceptance: "12-week cohort table renders in < 10s.", priority: "must", complexity: "L", businessValue: "high", dependencies: "Query engine", apisNeeded: "/queries/retention", dataNeeded: "CohortDefinition", edgeCases: "Sparse cohorts; very long tail", errorStates: "Show partial with note", adminControls: "—", audit: "—", security: "Tenant-scoped", futureEnhancements: "Predictive churn cohort", release: "mvp" },
      { id: "FEAT-006", name: "Segmentation", description: "Build user / event segments and reuse across charts.", userStory: "As an analyst, I save a segment and reuse it across dashboards.", acceptance: "Segment definition versioned and shared.", priority: "must", complexity: "M", businessValue: "high", dependencies: "—", apisNeeded: "/segments/*", dataNeeded: "Segment", edgeCases: "Segment depending on deleted event", errorStates: "Show breakage warning", adminControls: "Org-wide segment library", audit: "Segment edits logged", security: "RBAC: editor / viewer", futureEnhancements: "ML-suggested segments", release: "mvp" },
      { id: "FEAT-007", name: "Dashboards + sharing", description: "Compose charts and share with team or external link.", userStory: "As a growth PM, I share a dashboard at standup.", acceptance: "External link respects auth + RBAC.", priority: "must", complexity: "L", businessValue: "high", dependencies: "—", apisNeeded: "/dashboards/*", dataNeeded: "Dashboard, Chart", edgeCases: "Public link to private dashboard", errorStates: "Auth required state", adminControls: "Org sharing policy", audit: "View access logged", security: "Signed share links with expiry", futureEnhancements: "Dashboard-as-code via API", release: "mvp" },
      { id: "FEAT-008", name: "SQL editor", description: "Read-only SQL over the columnar store with autocomplete + saved queries.", userStory: "As a data analyst, I drop into SQL when the visual builder isn't enough.", acceptance: "Query timeout configurable; CSV export.", priority: "should", complexity: "L", businessValue: "high", dependencies: "Columnar store gateway", apisNeeded: "/sql/*", dataNeeded: "SqlQuery", edgeCases: "Runaway queries; cross-tenant SQL injection attempt", errorStates: "Hard timeout + helpful error", adminControls: "Per-role SQL access", audit: "Every SQL run logged with row scan estimate", security: "Read-only; per-tenant warehouse", futureEnhancements: "Notebook-style with charts inline", release: "v1" },
      { id: "FEAT-009", name: "Scheduled digests (Slack + email)", description: "Recurring snapshot of a dashboard sent to Slack or email.", userStory: "As a VP, I get my weekly KPIs in my inbox.", acceptance: "Delivery within 5 min of schedule.", priority: "should", complexity: "M", businessValue: "medium", dependencies: "Notifications", apisNeeded: "/digests/*", dataNeeded: "Digest", edgeCases: "Slack bot kicked from channel", errorStates: "Notify owner; pause", adminControls: "Tenant-wide digest policy", audit: "Send log", security: "Tenant-scoped tokens", futureEnhancements: "Anomaly-triggered digests", release: "v1" },
      { id: "FEAT-010", name: "User + role management", description: "Roles: admin, editor, viewer, sql-power-user.", userStory: "As an admin, I provision the team with the right access.", acceptance: "Permission changes effective in < 5s.", priority: "must", complexity: "M", businessValue: "high", dependencies: "Identity (Auth0 / SSO)", apisNeeded: "/users/*", dataNeeded: "User, Role", edgeCases: "SSO group mapping; role escalation request", errorStates: "Show approval workflow", adminControls: "Org-wide policy", audit: "Auth + role changes logged", security: "RBAC + SSO", futureEnhancements: "SCIM provisioning", release: "mvp" },
      { id: "FEAT-011", name: "Audit logging", description: "Append-only log for all sensitive actions (data access, role changes, exports).", userStory: "As a compliance owner, I review who accessed what.", acceptance: "Logs retained 13 months default; longer for regulated tenants.", priority: "must", complexity: "M", businessValue: "high", dependencies: "—", apisNeeded: "/audit/*", dataNeeded: "AuditEvent", edgeCases: "Bulk export request", errorStates: "—", adminControls: "Search + export", audit: "—", security: "Tamper-evident", futureEnhancements: "Streaming export to SIEM", release: "mvp" },
    ],
    kpis: [
      { id: "KPI-001", name: "Activation", definition: "% of new tenants who ship a dashboard in week 1", target: ">= 70%", cadence: "weekly" },
      { id: "KPI-002", name: "Time to first funnel", definition: "Median minutes from signup to first funnel saved", target: "< 1 day", cadence: "weekly" },
      { id: "KPI-003", name: "Gross retention", definition: "% of MRR retained QoQ excluding upgrades", target: ">= 95%", cadence: "quarterly" },
      { id: "KPI-004", name: "P95 query latency", definition: "P95 funnel + cohort query time at tenant median", target: "< 5s funnel; < 10s cohort", cadence: "daily" },
    ],
    businessRules:
      "Tenants pay per-MTU above 100K. Free tier capped at 100K events / month. Warehouse sync is included on Pro tier. SQL editor is read-only against tenant-scoped views; cross-tenant joins are impossible by construction.",
    edgeCases:
      "Schema drift in warehouse sync; tenant exceeds plan MTU; SQL runaway queries; ad blockers; SSO group mapping ambiguity; bulk export request; share link to deleted dashboard.",
  },
  nonfunctional: {
    availabilityTarget: "99.9% per tenant",
    rto: "1 hour",
    rpo: "5 minutes",
    performance: "Funnel + cohort p95 < 5s on 100M events; SQL timeout configurable per role",
    privacyPosture: "Per-tenant encryption keys; PII columns flagged + redactable; explicit consent for cross-tenant benchmark features (off by default).",
    auditability: "Every data access, role change, share-link creation, and SQL run captured in append-only audit log.",
    costBoundary: "Gross margin > 75% at $25K ACV.",
    supportModel: "Email 9-5 ET; Slack Connect for Pro; on-call for P1.",
    slos: [
      { id: "SLO-001", surface: "Funnel query", metric: "p95 latency on 100M events", target: "< 5s" },
      { id: "SLO-002", surface: "Cohort query", metric: "p95 latency on 100M events", target: "< 10s" },
      { id: "SLO-003", surface: "SDK ingestion", metric: "p95 ack latency", target: "< 200ms" },
      { id: "SLO-004", surface: "Warehouse sync", metric: "freshness", target: "<= 15 min behind source" },
      { id: "SLO-005", surface: "All write APIs", metric: "error rate (5xx)", target: "< 0.1%" },
    ],
  },
  dataTech: {
    entities: [
      { id: "ENT-001", name: "Tenant", description: "Customer org with billing, plan, and config.", sensitive: false, retention: "Indefinite while active" },
      { id: "ENT-002", name: "Project", description: "Logical scope of events within a tenant (e.g. \"prod\", \"staging\").", sensitive: false, retention: "Indefinite while active" },
      { id: "ENT-003", name: "Event", description: "Time-stamped event with properties + identity.", sensitive: true, retention: "13 months default; configurable per tenant" },
      { id: "ENT-004", name: "EndUser", description: "Anonymized end-user of the tenant's product.", sensitive: true, retention: "13 months" },
      { id: "ENT-005", name: "Dashboard / Chart / Segment", description: "User-built analytics objects.", sensitive: false, retention: "Indefinite while active" },
      { id: "ENT-006", name: "AuditEvent", description: "Append-only record of access + admin actions.", sensitive: true, retention: "13 months default" },
    ],
    integrations: [
      { id: "INT-001", system: "Snowflake / BigQuery / Redshift", direction: "inbound", protocol: "JDBC + REST", dataClass: "Events (PII risk)", notes: "Pull-based sync with schema mapping." },
      { id: "INT-002", system: "Slack", direction: "outbound", protocol: "Web API", dataClass: "Dashboard snapshots", notes: "Scheduled digests + alerts." },
      { id: "INT-003", system: "Auth0 / Okta / Azure AD", direction: "bidirectional", protocol: "OIDC + SCIM", dataClass: "PII (user identity)", notes: "SSO + provisioning." },
      { id: "INT-004", system: "Stripe", direction: "outbound", protocol: "REST", dataClass: "Billing", notes: "Subscription + usage billing." },
      { id: "INT-005", system: "Datadog", direction: "outbound", protocol: "OTLP/HTTPS", dataClass: "Infra metrics + traces", notes: "Observability; PII scrubbed." },
    ],
    dataResidency: "us-east-1 default; eu-west-1 for EU tenants. Per-tenant primary region pinning.",
    buildVsBuy:
      "Buy: identity (Auth0), billing (Stripe), Slack delivery, transactional email (SendGrid). Build: ingestion + columnar query layer + visual builder + multi-tenant admin.",
  },
  systemDesign: {
    expectedUsersTotal: 5_000_000,
    dau: 50_000,
    mau: 250_000,
    peakConcurrent: 2_000,
    avgRequestsPerUserPerDay: 80,
    readWriteRatio: "60:40",
    dataGrowthGBPerMonth: 5_000,
    notificationsPerDay: 5_000,
    availabilityTarget: "99.9%",
    latencyTargetMs: 5_000,
    geographicCoverage: "NA + EU",
    multiRegion: false,
    drNeeded: true,
    cachingStrategy: "Result cache for popular queries (TTL 5min); CDN for static; per-tenant precomputed daily aggregates.",
    dbScalingStrategy: "Postgres for tenant + config + audit; ClickHouse cluster for events (partitioned by tenant + time); cold partitions tiered to S3.",
    queueStrategy: "Kafka for ingestion; SQS for jobs (digest delivery, syncs); EventBridge for cross-service events.",
    notes: "Ingestion + columnar query are the dominant infra costs. Cold-tier policy on event partitions older than 13 months saves storage substantially.",
  },
  ai: {
    needsAI: false,
    kinds: [],
    ragNeeded: false,
    dataSources: "",
    modelProvider: "tbd",
    agentFramework: "none",
    observability: "none",
    vectorDb: "none",
    humanInLoop: false,
    guardrails: false,
    evaluation: false,
    promptManagement: false,
    auditLogs: false,
    privacyFiltering: false,
    notes: "AI features (anomaly detection, predictive churn) are a v2 candidate, not v1.",
  },
  compliance: {
    processesPersonalData: true,
    processesFinancialData: false,
    processesHealthData: false,
    frameworks: ["SOC2", "ISO27001", "GDPR", "OWASP-ASVS"],
    consentMgmt: true,
    auditLogs: true,
    encryptionAtRest: true,
    encryptionInTransit: true,
    rbacRequired: true,
    dataResidencyRequired: true,
    incidentResponseRequired: true,
    pentestCadence: "annual + per-major-release",
    threatModel:
      "Top threats: cross-tenant data leakage, SQL escape-hatch abuse, share-link enumeration. Mitigations: per-tenant encryption keys; tenant-scoped views; signed share links with expiry; runaway-query timeouts.",
  },
  gtm: {
    packaging: "saas",
    segments: "Mid-market B2B SaaS product + growth + data teams. Sweet spot: Series B-D with 50-300 employees.",
    buyerObjections: "Migration effort from incumbent; cost predictability; data residency for EU customers.",
    salesMotion: "PLG self-serve + assisted sales for >$25K ACV; design partners for enterprise tier.",
    channelStrategy: "Direct + Snowflake + AWS marketplace listings.",
    launchGeography: "US + Canada Q1; EU GA Q3 with eu-west-1 region.",
    complianceGating: "SOC 2 Type 1 by month 6; SOC 2 Type 2 by month 18; GDPR DPA + EU residency before EU GA.",
    pricingModel: "Per-MAU tiered + platform fee. Free up to 100K events / mo; Pro at $1K/mo + per-MTU.",
    acquisitionChannels: "Outbound to Heads of Product; conference (Product-Led Growth Summit, GLOW); content marketing on funnel/retention math; existing-customer referrals.",
    retentionStrategy: "Activation playbook (first dashboard in week 1); QBRs for Pro tier; Slack Connect channel for product-led + assisted accounts.",
    partnerships: "Snowflake + AWS marketplaces; Segment partner integration.",
    competitors: "Amplitude, Mixpanel, Heap, PostHog, in-house ClickHouse setups.",
    positioning:
      "For mid-market B2B SaaS product teams who want first-party analytics without paying premium prices, our platform is warehouse-native, transparent, and SOC 2 / GDPR-ready — without the lock-in or 7-figure renewal of incumbents.",
    marketingKpis: "Pipeline / quarter; PLG conversion (free → paid); CAC payback < 18 months.",
  },
  governance: {
    owner: "VP Product",
    approvers: "VP Eng, Head of Data, Head of Privacy",
    dependencies: "Snowflake / BigQuery / Redshift partner program access; AWS spend commit; Auth0 enterprise.",
    thirdParties: "Auth0, Stripe, AWS, Datadog, SendGrid, Snowflake, BigQuery, Redshift.",
    legalReviews: "DPA + subprocessor list; GDPR data processing terms.",
    procurementReviews: "AWS spend commit; Auth0 enterprise sign-off.",
    unvalidatedAssumptions: "Mid-market teams will accept warehouse-native sync vs. SDK-only; per-MTU pricing matches buyer mental model.",
    decisionConfidence: "high",
  },
  stakeholders: [
    { id: "s1", role: "VP Product", responsibility: "Roadmap + design partners" },
    { id: "s2", role: "VP Engineering", responsibility: "Multi-tenant platform + on-call" },
    { id: "s3", role: "Head of Data", responsibility: "Query engine + warehouse connectors" },
    { id: "s4", role: "Head of Privacy", responsibility: "GDPR + tenant isolation" },
  ],
  decisions: [
    { id: "ADR-001", title: "ClickHouse for events (not Postgres / Druid / Pinot)", context: "Need columnar analytics scale.", decision: "ClickHouse cluster for events; partition by tenant + time.", alternatives: "Postgres+TimescaleDB; Druid; Pinot.", consequences: "Higher infra cost than Postgres; sub-5s queries on 100M+ events.", status: "accepted", confidence: "high" },
    { id: "ADR-002", title: "Warehouse-native sync from day 1", context: "Buyer differentiator vs. incumbents.", decision: "Build Snowflake + BigQuery + Redshift connectors for v1 GA.", alternatives: "SDK-only v1, connectors v2.", consequences: "More upfront eng work; major sales win.", status: "accepted", confidence: "medium" },
    { id: "ADR-003", title: "Per-tenant encryption keys", context: "SOC 2 + buyer trust.", decision: "Customer-managed keys via AWS KMS; rotate quarterly.", alternatives: "Single master key; HSM-backed keys for enterprise only.", consequences: "More ops complexity; required for trust posture.", status: "accepted", confidence: "high" },
  ],
  risks: [
    { id: "RISK-001", description: "Migration friction from Amplitude / Mixpanel keeps deals stuck.", likelihood: "high", impact: "high", mitigation: "Free migration tooling; design-partner case studies showing time-to-replace." },
    { id: "RISK-002", description: "ClickHouse cluster cost blows past margin target at scale.", likelihood: "medium", impact: "high", mitigation: "Cold-tier policy; per-tenant resource quotas; pre-aggregation for top 80% of queries." },
    { id: "RISK-003", description: "GDPR data residency contract terms slow EU deals.", likelihood: "high", impact: "medium", mitigation: "Pre-built EU DPA template; eu-west-1 region from day 1 of EU GA." },
  ],
  assumptions: [
    { id: "ASM-001", text: "PLG funnel converts >= 5% of free → paid in 90 days.", validated: false },
    { id: "ASM-002", text: "Warehouse-native is a real GTM differentiator (not just a feature checkbox).", validated: false },
    { id: "ASM-003", text: "Mid-market buyers will accept SOC 2 Type 1 to start with Type 2 promised in 12 months.", validated: true },
  ],
  openQuestions: [
    { id: "Q-001", text: "Do we ship reverse-ETL out (CDP-like) or stay query-only in v1?", owner: "VP Product" },
    { id: "Q-002", text: "Per-tenant ClickHouse cluster vs. shared with row-level isolation — which scales better?", owner: "Head of Data" },
  ],
  progress: ALL_COMPLETE,
};

export const SAAS_TEMPLATE: TemplateMeta = {
  id: "saas-analytics",
  title: "B2B SaaS analytics dashboard",
  blurb:
    "Multi-tenant product analytics: SDK + warehouse sync, funnels, cohorts, dashboards, SQL escape hatch.",
  vertical: "B2B SaaS · product analytics",
  stackChips: ["Next.js", "NestJS", "Postgres", "ClickHouse", "AWS"],
  complianceChips: ["SOC 2", "ISO 27001", "GDPR"],
  scaleChip: "B2B SaaS · 50K DAU · 5TB / mo",
  payload,
};
